### PR TITLE
BUGFIX: Validate DateRanges more correctly

### PR DESCRIPTION
**Pull request by mficzel**
Use correct DateTimeRangeValidator for Date Fields if Value Ranges are defined.

### CODE REVIEW

**Comment by mficzel** [comment]
@jonnitto hope this helps ... did not test and typed directly in the github editor.

**Comment by jonnitto** [comment]
I would do it like this:

```
dateRangeValidatorOptions = Neos.Fusion:DataStructure {
    @process.filter = ${Array.filter(value)}
    earliestDate = ${q(node).property('earliestDate')}
    earliestDate.@process.toString = ${value ? Date.format(value, 'Y-m-d') : null}
    latestDate = ${q(node).property('latestDate')}
    latestDate.@process.toString = ${value ? Date.format(value, 'Y-m-d') : null}
}
renderer.@process.addDateRangeValidator = ${Array.length(props.dateRangeValidatorOptions) ? value.validator('DateTimeRange', props.dateRangeValidatorOptions) : value}
```

`dateRangeValidatorOptions` is always an array, so it make sense to check if it has some value in it

**Comment by jonnitto** [comment]
Yep, you're right…

**Comment by jonnitto** [comment]
Yes, you can merge it. But we have to fix also https://github.com/neos/flow-development-collection/issues/3323

**Pull request merged**
